todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todo_app.urls')),
    path('admin/', admin.site.urls),
]

todo_app/urls.py
from django.urls import path
from .views import ( TodoListCreateView, TodoDeleteView, TodoUpdateView,)

app_name = 'todo'

urlpatterns = [
    path('todo_list/', TodoListCreateView.as_view(), name='todo-create'),
    path('update/<int:pk>/', TodoUpdateView.as_view(), name='todo-update'),
    path('delete/<int:pk>/', TodoDeleteView.as_view(), name='todo-delete'),
]

todo_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
# Create your models here.

class Todo(models.Model):
    assignment = models.TextField()
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=datetime.now())
    due = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('todo:todo-create')

todo_app/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import DateInput
from .models import Todo


class DateInput(forms.DateInput):
    input_type = 'date'

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['assignment', 'completed', 'due']
        widgets = {
            'due': DateInput(format='%d/%m/%Y %H:%i'),
        }

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import (
            ListView,
            CreateView,
            DeleteView,
            UpdateView
)

from .models import Todo
from .forms import TodoForm
# Create your views here.

# class TodoListView(ListView):
#     template_name = 'todo/todo_list.html'
#     queryset = Todo.objects.all()


class TodoListCreateView(CreateView):
    model = Todo
    template_name = 'todo/todo_list.html'
    form_class = TodoForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["objects"] = self.model.objects.order_by('-completed')
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    # def get_success_url(self):
    #     return '/'

class TodoDeleteView(DeleteView):
    model = Todo
    def get_success_url(self):
        return reverse('todo:todo-create')

class TodoUpdateView(UpdateView):
    model = Todo
    fields = ['completed']

todo_app/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>To-do list</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw==" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  </head>
  <body>
    {% block content%}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.js" integrity="sha512-+UiyfI4KyV1uypmEqz9cOIJNwye+u+S58/hSwKEAeUMViTTqM9/L4lqu8UxJzhmzGpms8PzFJDzEqXL9niHyjA==" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

todo_app/templates/todo/todo_list.html
{% extends 'todo/base.html' %}

{% block content %}

<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">Todo list</h4>
                          <form action="." method="POST">
                            {% csrf_token %}
                            {% if form.assignment.errors %}
                            <ul>
                              <li><strong>This field is required</strong></li>
                            </ul>
                            {% endif %}
                            <div class="add-items d-flex">
                            <input type="text"  name="assignment" class="form-control todo-list-input" placeholder="What do you need to do?" required>
                            <input name="due" id="dtpicker" class="form-control todo-list-input" placeholder="Enter due date.." autocomplete="off">
                            <input type='submit' value='Add' class="add btn btn-primary font-weight-bold todo-list-add-btn"></div>
                          </form>
                          <div class="list-wrapper">
                            <ul class="d-flex flex-column-reverse todo-list">
                              {% for instance in objects %}
                                <li>
                                    <div class="form-check"><form action="{% url 'todo:todo-update' instance.id %}" method="POST">{% csrf_token %}<label class="checkbox"> <input name="completed" onclick="this.form.submit();" type="checkbox" class="checkbox" value="{{instance.id}}" {% if instance.completed %} checked {% endif %}></label>
                                    {% if instance.due == None %}
                                      <span>{{instance.assignment}}</span>
                                    {% elif instance.completed %}
                                      <strike>{{instance.assignment}}</strike><p id="countdown-{{forloop.counter}}" class="countd" data-num="{{objects|length}}" data-id="{{instance.id}}" style="display:none;">{{instance.due|date:"m/d/Y, H:i:s"}}</p><span style="display:none;" id="cd-timer-{{forloop.counter}}"></span>
                                    {%else%}
                                      <span>{{instance.assignment}}</span><p id="countdown-{{forloop.counter}}" class="countd" data-num="{{objects|length}}" data-id="{{instance.id}}" style="display:none;">{{instance.due|date:"m/d/Y, H:i:s"}}</p><span class="cd-timer" id="cd-timer-{{forloop.counter}}"></span>
                                    {% endif %}
                                    </div></form>
                                    <form action="{% url 'todo:todo-delete' instance.id %}" method="POST">
                                      {% csrf_token %}
                                     <button type="submit" class="fav-button"><i class="remove mdi mdi-close-circle-outline"></i></button>
                                   </form>
                                </li>
                              {% endfor %}
                            </ul>
                              </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(function () {
  $("#dtpicker").datetimepicker({
    format: 'd/m/Y H:i',
    minDate: '0',
  });
});

</script>

<script>
// Set the date we're counting down to

function createCountDown(elementId, date) {

var countDownDate = new Date(date).getTime();
// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Function to add leading zeros
  var addLeadingZeros = function(number){
    return (number < 10) ? "0" + number : number;
  }

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Output the result in an element with id="demo"
  document.getElementById(elementId).innerHTML =" Due: " + addLeadingZeros(days) + "d " + addLeadingZeros(hours) + "h "
  + addLeadingZeros(minutes) + "m " + addLeadingZeros(seconds) + "s ";

  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById(elementId).innerHTML = "EXPIRED";
  }
}, 1000);
}

//Output the results to element Id's
var numObjects = document.getElementsByClassName("countd")[0].getAttribute("data-num");
for (var i=1; i<=numObjects; i++){
  if(document.getElementById("countdown-"+i.toString()) !== null){
    var dateTime = document.getElementById("countdown-"+i.toString()).textContent;
    createCountDown("cd-timer-"+i.toString(), dateTime)
  }
}

</script>



{% endblock %}